name: 'Binadox Infrastructure-As-Code analyzer'
description: 'Analyze your Infrastructure-As-Code'
inputs:
  binadox-server-url:  # id of input
    description: 'Binadox server url'
    required: true
    default: 'https://httpbin.org/post'
  binadox-project-name:
    description: 'project name as defined at Binadox'
    required: true
    default: 'my-project'
  binadox-secret-token:
    description: 'Binadox secret token'
    required: true
    default: 'XXXX'
  github-event-name:
    description: 'github-event-name'
    required: true
    default: ''
  github-event-action:
    description: 'github-event-name'
    required: true
    default: ''  
outputs:
  status: 
    description: 'Status of request to Binadox'
runs:
  using: 'node20'
  main: 'index.js'
