on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Send request to Binadox
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Initiating analysis by Binadox
        uses: ./ # Uses an action in the root directory
        id: binadox-tester
        with:
          binadox-secret-token: '${{ secrets.BINADOX_TOKEN }}'
          binadox-server-url: 'https://httpbin.org/post'
          binadox-project-name: 'zopa'
      # Use the output from the `hello` step
      - name: Get the status
        run: echo "status ${{ steps.binadox-tester.outputs.status }}"
